/**
 * Auth Email Service
 *
 * Architecture note:
 * ─────────────────────────────────────────────────────────────────────────────
 * Currently, Supabase handles all authentication emails (signup verification,
 * password reset, magic links) natively using its built-in mailer or a
 * configured Custom SMTP provider.
 *
 * To switch to a custom transactional provider (e.g. Resend, SendGrid):
 *
 *  1. In your Supabase Dashboard → Project Settings → Auth → SMTP Settings,
 *     enter the SMTP credentials for your provider (Resend, SendGrid, etc.).
 *     This requires ZERO code changes in the application.
 *
 *  2. For full custom control (custom API routes, templates served from code),
 *     use `supabase.auth.admin.generateLink()` (server-side only) to generate
 *     a one-time auth link, then use the `sendAuthEmail()` function below to
 *     dispatch it through your preferred provider.
 *
 * The interface below is the contract. Swap the implementation inside
 * `sendAuthEmail` to change providers without touching callers.
 * ─────────────────────────────────────────────────────────────────────────────
 */

export type AuthEmailType =
  | "signup_confirmation"
  | "password_reset"
  | "magic_link";

export interface AuthEmailPayload {
  to: string;
  type: AuthEmailType;
  /** The one-time action URL generated by Supabase */
  actionUrl: string;
  /** Recipient's display name (optional) */
  name?: string;
}

const SENDER_NAME = "Shop Kareta";
const SENDER_EMAIL = "shopkareta@gmail.com";

/**
 * Sends a branded authentication email.
 *
 * Provider-agnostic — swap the implementation inside to change providers.
 * Current implementation: uses Resend HTTP API.
 * To switch providers: update only the fetch call / SDK call below.
 */
export async function sendAuthEmail(payload: AuthEmailPayload): Promise<{ success: boolean; error?: string }> {
  const { to, type, actionUrl, name } = payload;

  const subjectMap: Record<AuthEmailType, string> = {
    signup_confirmation: "Verify your email – Shop Kareta",
    password_reset: "Reset your password – Shop Kareta",
    magic_link: "Your sign-in link – Shop Kareta",
  };

  const bodyMap: Record<AuthEmailType, string> = {
    signup_confirmation: buildVerificationHtml(actionUrl, name),
    password_reset: buildPasswordResetHtml(actionUrl, name),
    magic_link: buildMagicLinkHtml(actionUrl, name),
  };

  // ── Provider: Resend ──────────────────────────────────────────────────────
  // To switch to SendGrid or another provider, replace only this block.
  const RESEND_API_KEY = process.env.RESEND_API_KEY;

  if (!RESEND_API_KEY) {
    console.warn("[AuthEmailService] RESEND_API_KEY not set. Email not sent.");
    return { success: false, error: "Email provider not configured." };
  }

  try {
    const response = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${RESEND_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: `${SENDER_NAME} <${SENDER_EMAIL}>`,
        to: [to],
        subject: subjectMap[type],
        html: bodyMap[type],
      }),
    });

    if (!response.ok) {
      const data = await response.json();
      return { success: false, error: data?.message || "Failed to send email." };
    }

    return { success: true };
  } catch (err: any) {
    return { success: false, error: err.message };
  }
  // ── End Provider Block ─────────────────────────────────────────────────────
}

// ── HTML Builders ─────────────────────────────────────────────────────────────

function emailWrapper(content: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1.0"/>
  <style>
    body{font-family:'Helvetica Neue',Arial,sans-serif;background:#F7F8FA;color:#0D1B2A;margin:0;padding:0}
    .wrapper{padding:40px 16px}
    .container{max-width:560px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,.06)}
    .header{background:#0F6B46;padding:26px 40px;text-align:center}
    .brand{font-size:20px;font-weight:700;color:#fff}
    .body{padding:40px;text-align:center}
    .title{font-size:22px;font-weight:700;margin-bottom:12px}
    .text{font-size:15px;color:#5A6A7A;line-height:1.7;margin-bottom:28px}
    .btn{display:inline-block;background:#0F6B46;color:#fff!important;text-decoration:none;padding:14px 36px;border-radius:12px;font-size:15px;font-weight:600;margin-bottom:20px}
    .small{font-size:12px;color:#A0ADB8;word-break:break-all}
    .small a{color:#0F6B46}
    hr{border:none;border-top:1px solid #EAECF0}
    .footer{padding:24px 40px;text-align:center;font-size:12px;color:#A0ADB8;line-height:1.7}
    .footer a{color:#5A6A7A;text-decoration:none}
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="container">
      <div class="header"><span class="brand">🛒 Shop Kareta</span></div>
      <div class="body">${content}</div>
      <hr/>
      <div class="footer">
        Need help? <a href="mailto:shopkareta@gmail.com">shopkareta@gmail.com</a><br/>
        © 2025 Shop Kareta. All rights reserved.
      </div>
    </div>
  </div>
</body>
</html>`;
}

function buildVerificationHtml(url: string, name?: string): string {
  return emailWrapper(`
    <h1 class="title">Verify Your Email</h1>
    <p class="text">Hi${name ? ` ${name}` : ""}! Thanks for creating your Shop Kareta account.<br/>Click below to verify your email address and get started.</p>
    <a href="${url}" class="btn">Verify My Email</a>
    <p class="small">Button not working? <a href="${url}">Click here</a></p>
  `);
}

function buildPasswordResetHtml(url: string, name?: string): string {
  return emailWrapper(`
    <h1 class="title">Reset Your Password</h1>
    <p class="text">Hi${name ? ` ${name}` : ""}! We received a request to reset your Shop Kareta password.<br/>Click below to choose a new password. This link expires in 1 hour.</p>
    <a href="${url}" class="btn">Reset Password</a>
    <p class="small">Didn't request this? You can safely ignore this email.</p>
  `);
}

function buildMagicLinkHtml(url: string, name?: string): string {
  return emailWrapper(`
    <h1 class="title">Your Sign-In Link</h1>
    <p class="text">Hi${name ? ` ${name}` : ""}! Click the button below to sign in to Shop Kareta.<br/>This link can only be used once and expires in 1 hour.</p>
    <a href="${url}" class="btn">Sign In to Shop Kareta</a>
    <p class="small">Didn't request this? You can safely ignore this email.</p>
  `);
}
